# Generated by Django 3.2.5 on 2021-07-25 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unic_name', models.IntegerField(unique=True)),
                ('first_name', models.TextField(max_length=20)),
                ('second_name', models.TextField(max_length=50)),
                ('middle_name', models.TextField(max_length=20)),
                ('speciality', models.CharField(choices=[('consultant', 'Consultant'), ('master', 'Master'), ('service_staff', 'Service staff')], max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('tg_nick', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unic_name', models.IntegerField(unique=True)),
                ('first_name', models.TextField(max_length=20)),
                ('second_name', models.TextField(max_length=50)),
                ('middle_name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tg_nick', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('apl_type', models.CharField(choices=[('repair', 'Repair'), ('service', 'Service'), ('consultation', 'Consultation')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_work', 'In work'), ('closed', 'Closed')], max_length=7)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(help_text='Deadline')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee')),
            ],
        ),
    ]
