# Generated by Django 3.2.5 on 2021-07-25 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='end_date',
            field=models.DateField(help_text='Deadline', validators=[django.core.validators.MinValueValidator(models.DateField(auto_now=True))]),
        ),
    ]
